### ISSUE TITLE
[FEATURE]: Config File Support

### ISSUE THREAD

**Issue by haasy** [mobile-directing-system/mds-desktop#10]
### Feature Motivation

Basic Config File support to load a config file into a globally available read-only config object for e.g. the backend base URL. Necessary to support configurability of the developed app.

### Solution Description

Add code to load a json config files and store the configuration in a globally available read-only object.

### feature_acceptance_criteria

- [ ] code to read json config files and  store the configuration
- [ ] document available config keys

**Comment by lefinal** [comment]
wouldn't it be easier to set configuration parameters in the app directly? basic configuration parameters like server url might be set as with the mattermost desktop app.
