### ISSUE TITLE
[FEATURE]: Add edit and  create for operations

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#146]
### Feature Motivation

Creating and editing operations is a core functionality.

### Solution Description

Add a create/edit view for operations.

### feature_acceptance_criteria

- [ ] All relevant operation fields (create/edit)
- [ ] Close, Delete, Create/Save buttons
- [ ] Tested

**Comment by lefinal** [comment]
Closed via #160
