### ISSUE TITLE
[FEATURE]: Add edit and create for groups

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#147]
### Feature Motivation

Creating and editing groups is a core functionality.

### Solution Description

Add a create/edit view for groups.

### feature_acceptance_criteria

- [ ]  All relevant operation fields  (create/edit)
- [ ]  Close, Delete, Create/Save buttons
- [ ]  Tested

**Comment by lefinal** [comment]
Closed via #160
