### ISSUE TITLE
[FEATURE]:  User Management

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#17]
### Feature Motivation

As a User  I want to edit users in particular I want to delete users, create new ones and update existing users, therefore I need an overview of all Users.

### Solution Description

Create the certain components and link them with the side/navbar, so that they are accessible.

### feature_acceptance_criteria

- [ ] User-create view
- [ ] Update user view
- [ ] Delete user prompt
- [ ] User-list 

### Related Issues

#13

**Comment by lefinal** [comment]
idea for ui see #6

**Comment by ltodtuu** [comment]
Rework: NoModals - all in 1 site
