### ISSUE TITLE
[FEATURE]: Intel Creation 

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#181]
### Feature Motivation

Core functionallity.

### Solution Description

https://www.figma.com/proto/74DJVEGNW5Ji9Ok4eeZv6l/Mobile-Directing-System?node-id=248-2664&scaling=scale-down&page-id=104%3A16&starting-point-node-id=248%3A2664&show-proto-sidebar=1

### feature_acceptance_criteria

- [ ] Implemented
- [ ] Documented
- [ ] Tested

**Comment by AtLars** [comment]
Closed because of redesign of message creation.
