### ISSUE TITLE
[BUG]: Intel creation - Address book entries

### ISSUE THREAD

**Issue by AtLars** [mobile-directing-system/mds-desktop#192]
### Bug Description

Occurence: Assign an address book entry for an intel delivery (Intel creation page)
Address book entry selection does not show the correct users that are available.
Only address book entries are shown that are assigned to the current user.

### Expected Behavior

Address book entries that do not have a user assigned should be shown in the list.

### Steps to Reproduce

-

### Possible Solutions

-

### Further Information

-

**Comment by MMV-pro** [comment]
Seems to be a server-related bug. Can you review the incoming and outcoming requests of the server @AtLars ?
