### ISSUE TITLE
[CHANGE]: dont allow national emergency as priority

### ISSUE THREAD

**Issue by MMV-pro** [mobile-directing-system/mds-desktop#198]
### Desired Change

State emergency please leave out.

---------------------------------------------

Staatsnot bitte rauslassen.

### Reason/Motivation for Change

Feedback from Schuhmacher via Mail from 2023-04-26

**Comment by MMV-pro** [comment]
I think it makes sense to wait for further details about the possible priorities.

Comment from Schuhmacher: For importance, however, you should not only be able to specify "Simple - Immediate - Flash", but also something finer.
Flash", but should be more finely graded.

-----

Bei Wichtigkeit sollte man aber nicht nur „Einfach - Sofort -
Blitz“ angeben können, sondern etwas feiner abstufen.


See: https://cloudstore.uni-ulm.de/apps/files/?dir=/MDS&openfile=80053910

**Comment by AtLars** [comment]
National emergency should not be included
