### ISSUE TITLE
[FEATURE]: Create User

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#5]
### Feature Motivation

As a user I want to be able to create accounts for my colleagues, delete Accounts and see other users.

### Solution Description

Create a UI Scheme to gather all data needed for user creation and deletion requests.

### feature_acceptance_criteria

Valid data creates a User successfully and invalid gets response message and shows what went wrong.

-[] User can be created
-[] User can be deleted 
-[] A list of users is shown

### Related Issues

#3

**Comment by lefinal** [comment]
@ltodtuu see #6 for possible design
