### ISSUE TITLE
[BUG]: User deletion of newly created & updated users

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#54]
### Bug Description

When deleting a newly created user --> all recently created users get deleted.

When updating username of a user a new user with the updated username is shown 
--> deleting any of both results in both being deleted

### Expected Behavior

only 1 user should be deleted at a time

### Steps to Reproduce

create multiple new users, delete any of them. 

update a users username and delte any of the 2.

### Possible Solutions

Problem maybe in state userlist.

**Comment by haasy** [comment]
The behavior of the deletion with the updated users is intended and follow from the bug described in Issue #55. As such this bug was also fixed in 0ac1c93348a1b788b0f704bd126c8832c437d02b.

The second behavior can't be replicated. Maybe you mistook some of the first behavior for the second one?
